tenantId: ${env:TENANT_ID}
clientId: ${env:CLIENT_ID}
clientSecret: ${env:CLIENT_SECRET}
clientIdAccManagement: ${env:CLIENT_ID_ACC}
clientSecretAccManagement: ${env:CLIENT_SECRET_ACC}
frontEndUrl: ${env:FRONTEND_URL:-https://pip-frontend.staging.platform.hmcts.net}
dataManagementApi:
  scopes: ${env:DATA_MANAGEMENT_AZ_API}/.default
  url: ${env:DATA_MANAGEMENT_URL:-https://pip-data-management.staging.platform.hmcts.net}
accountManagementApi:
  scopes: ${env:ACCOUNT_MANAGEMENT_AZ_API}/.default
  url: ${env:ACCOUNT_MANAGEMENT_URL:-https://pip-account-management.staging.platform.hmcts.net}
publicationServicesApi:
  scopes: ${env:PUBLICATION_SERVICES_AZ_API}/.default
  url: ${env:PUBLICATION_SERVICES_URL:-https://pip-publication-services.staging.platform.hmcts.net}
testSystemAdminId: ${env:TEST_SYSTEM_ADMIN_ID}
testVerifiedUserId: ${env:TEST_VERIFIED_USER_ID}